### ISSUE TITLE
Gasire nume domeniu

### ISSUE THREAD

**Issue by zsoltmathe** [onelogic/myDoctor#1]
Pt pagina gen doctolib sa gasim numele de domeniu

Astea ar fi dispo:

doctorama.ro
doctopedia.ro
listadoctori.ro
rezervaredoctor.ro

Ne gandeam la doctorulmeu.ro dar e luat:-(

Idei?

**Comment by adrianleoveanu** [comment]
Ladoctor

**Comment by amatyas** [comment]
Mi se pare beton propunerea lui leo

ladoctor.ro
Le 30 avr. 2016 9:46 AM, "adrianleoveanu" <notifications@github.com> a
écrit :

> Ladoctor

**Comment by zsoltmathe** [comment]
domeniul este inregistrat :(

**Comment by amatyas** [comment]
ar mai fi disponibil 

quickmed.ro


sincer mie imi pare ok doctorama.ro

**Comment by SoosLaci** [comment]
medlogic.ro - a onelogic product

**Comment by amatyas** [comment]
s-a cumparat doctorama.ro si am si instalat site-ul acolo ...e o versiune in curs de dezvoltare deci nu va mirati daca mai sunt bug-uri sau linkuri care nu merg
